import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { runtime, LOCAL_SETUP } from '../scripts/local-runtime.mjs';
test('content lifecycle, authorization, validation, CORS and video ranges',async t=>{
  const mf=await runtime();t.after(()=>mf.dispose());
  const origin='https://saleh.example';
  const request=(path,method='GET',body,who='owner',extra={})=>{
    const headers={Origin:origin,...extra};if(who)headers['oai-authenticated-user-id']=who;
    let data=body;if(body && !(body instanceof Uint8Array)){data=JSON.stringify(body);headers['Content-Type']='application/json';}
    return mf.dispatchFetch(origin+path,{method,headers,body:data});
  };
  assert.equal((await request('/api/admin/media','GET',undefined,null)).status,401);
  assert.equal((await request('/api/claim','POST',{token:LOCAL_SETUP},null)).status,401);
  assert.equal((await request('/api/claim','POST',{token:'f'.repeat(64)})).status,403);
  assert.equal((await request('/api/claim','POST',{token:LOCAL_SETUP},'owner',{Origin:'https://evil.example'})).status,403);
  assert.equal((await request('/api/claim','POST',{token:LOCAL_SETUP})).status,200);
  assert.equal((await request('/api/claim','POST',{token:LOCAL_SETUP},'other')).status,409);
  assert.equal((await request('/api/admin/media','GET',undefined,'other')).status,403);
  assert.equal((await request('/api/admin/media','POST',new Uint8Array([1,2]),'owner',{'Content-Type':'text/html'})).status,415);
  assert.equal((await request('/api/admin/media','POST',new Uint8Array([1,2]),'owner',{'Content-Type':'image/png'})).status,415);
  const image=new Uint8Array(await readFile('dist/assets/original-logo.jpg'));
  const upload=await request('/api/admin/media','POST',image,'owner',{'Content-Type':'image/jpeg'});assert.equal(upload.status,201);
  const {item}=await upload.json();
  assert.equal((await (await request('/api/gallery','GET',undefined,null)).json()).items.length,0);
  assert.equal((await request(item.url,'GET',undefined,null)).status,404);
  assert.equal((await request(item.url,'GET')).status,200);
  assert.equal((await request('/api/admin/media/'+item.id,'PATCH',{title:'',caption:'',published:true})).status,400);
  assert.equal((await request('/api/admin/media/'+item.id,'PATCH',{title:'x'.repeat(121),caption:'',published:true})).status,400);
  assert.equal((await request('/api/admin/media/'+item.id,'PATCH',{title:'A title',caption:'Caption',published:true},'owner',{Origin:'https://evil.example'})).status,403);
  const title='<img src=x onerror=alert(1)> שלום';
  assert.equal((await request('/api/admin/media/'+item.id,'PATCH',{title,caption:'شرح بالعربية',published:true,first:true})).status,200);
  const publicResponse=await request('/api/gallery','GET',undefined,null,{Origin:'https://moosev133.github.io'});
  assert.equal(publicResponse.headers.get('Access-Control-Allow-Origin'),'https://moosev133.github.io');
  assert.equal((await publicResponse.json()).items[0].title,title);
  assert.equal((await request('/api/gallery','GET',undefined,null,{Origin:'https://evil.example'})).headers.get('Access-Control-Allow-Origin'),null);
  assert.equal((await request(item.url,'GET',undefined,null)).status,200);
  const range=await request(item.url,'GET',undefined,null,{Range:'bytes=0-9'});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,10);
  assert.equal(range.headers.get('Content-Range'),`bytes 0-9/${image.byteLength}`);
  const suffix=await request(item.url,'GET',undefined,null,{Range:'bytes=-5'});assert.equal((await suffix.arrayBuffer()).byteLength,5);
  assert.equal((await request(item.url,'GET',undefined,null,{Range:'bytes=999999999-'})).status,416);
  assert.equal((await request('/api/admin/media/'+item.id,'PATCH',{title:'Saved',caption:'',published:false})).status,200);
  assert.equal((await request(item.url,'GET',undefined,null)).status,404);
  assert.equal((await request('/api/admin/media/'+item.id,'DELETE',undefined,null)).status,401);
  assert.equal((await request('/api/admin/media/'+item.id,'DELETE')).status,200);
  assert.equal((await request(item.url)).status,404);
  const film=new Uint8Array(await readFile('tests/fixtures/preview.mp4'));
  const videoUpload=await request('/api/admin/media','POST',film,'owner',{'Content-Type':'video/mp4'});assert.equal(videoUpload.status,201);
  const video=(await videoUpload.json()).item;assert.equal(video.type,'video');
  await request('/api/admin/media/'+video.id,'PATCH',{title:'Film',caption:'',published:true});
  const filmBytes=await (await request(video.url,'GET',undefined,null)).arrayBuffer();assert.deepEqual(new Uint8Array(filmBytes),film);
  const seek=await request(video.url,'GET',undefined,null,{Range:'bytes=500-999'});assert.equal(seek.status,206);assert.deepEqual(new Uint8Array(await seek.arrayBuffer()),film.slice(500,1000));
  assert.equal((await request('/api/admin/media','POST',new Uint8Array(12*1024*1024+1),'owner',{'Content-Type':'image/png'})).status,413);
  await request('/api/admin/media/'+video.id,'DELETE');
  const bucket=await mf.getR2Bucket('BUCKET');assert.equal((await bucket.list()).objects.length,0);
  const db=await mf.getD1Database('DB');assert.equal((await db.prepare('SELECT count(*) AS total FROM media').first()).total,0);
  assert.equal((await request('/admin')).headers.get('X-Robots-Tag'),'noindex, nofollow');
  const config=await request('/.openai/hosting.json');assert.equal(config.status,404);
});
